check:
  handler: 02_pipeline/check.main
  description: Checks for package on PyPi via the API
  runtime: python3.8
  timeout: 30
  memorySize: 256
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-p38-requests:7
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPython:6

deploy:
  handler: 02_pipeline/deploy.main
  description: Deploys functions to multiple regions
  runtime: python3.9
  timeout: 600
  memorySize: 512
  environment:
    POWERTOOLS_SERVICE_NAME: Klayers.Deploy
    EXPIRY_DAYS: 365
  iamRoleStatementsName: ${self:provider.stage}-deploy
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:UpdateItem
      Resource: 
      - ${self:custom.dbArn}
      - ${self:custom.dbArn}/index/package_global_by_python_version
    - Effect: Allow
      Action:
      - lambda:AddLayerVersionPermission
      - lambda:GetLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
       - lambda:PublishLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
      - s3:GetObject
      Resource: ${self:custom.s3LayersArn}/*
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: ${ssm:/common-service/${self:provider.stage}/CommonServiceApi/arn}/GET*
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPython:6
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-p39-aws-requests-auth:11

combine_packages:
  handler: 02_pipeline/combine.main
  description: Checks for package on PyPi via the API
  runtime: python3.9
  timeout: 600
  memorySize: 1769  # exactly one vcpu
  iamRoleStatementsName: ${self:provider.stage}-combinep39
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:PutObjectAcl
    - s3:GetObject
    Resource: ${self:custom.s3LayersArn}/*
  - Effect: Allow
    Action:
    - s3:ListBucket
    Resource: ${self:custom.s3LayersArn}
  - Effect: Allow
    Action:
    - lambda:AddLayerVersionPermission
    - lambda:GetLayerVersion
    Resource: "*"
  - Effect: Allow
    Action:
    - lambda:PublishLayerVersion
    Resource: "*"
  - Effect: Allow
    Action: execute-api:Invoke
    Resource: ${ssm:/common-service/${self:provider.stage}/CommonServiceApi/arn}/GET*
  layers:
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:37
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-p39-aws-requests-auth:11